# Generated by Django 5.1.15 on 2026-07-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_attachment_uuid_upload_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bitrix_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='bitrix_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='agency_bitrix_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='bitrix_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
