# Generated by Django 5.1.15 on 2026-07-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_alter_project_bitrix_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
