# Generated by Django 5.1.15 on 2026-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_support_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Manager review'), ('pending_client', 'Pending client'), ('disputed', 'Disputed'), ('accepted', 'Accepted'), ('paid', 'Paid')], db_index=True, default='draft', max_length=32),
        ),
    ]
