# Generated by Django 5.1.15 on 2026-08-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_workreport_dismissed'),
        ('portals', '0008_uniq_active_deal_per_deal_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('agency_bitrix_task_id', ''), _negated=True), fields=('agency_bitrix_task_id',), name='uniq_task_agency_bitrix_id'),
        ),
    ]
